### ISSUE TITLE
Tests failing on ubuntu-latest python 3.9 CI - Shader compilation error in GL_VERTEX_SHADER:

### ISSUE THREAD

**Issue by GenevieveBuckley** [napari/napari.github.io#126]
The CI tests failing on ubuntu-latest python 3.9: https://github.com/napari/napari.github.io/pull/125/checks?check_run_id=2413215369

It looks like there's some kind of compilation error causing the failure in `test_docs.py::test_doc_code_cells[guides/stable/magicgui.md]`

Here's the log:
```
test_docs.py::test_doc_code_cells[guides/stable/magicgui.md] FAILED      [100%]

=================================== FAILURES ===================================
________________ test_doc_code_cells[guides/stable/magicgui.md] ________________
CALL ERROR: Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/visuals/visual.py", line 595, in draw
    v.draw()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/visuals/visual.py", line 442, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/visuals/shaders/program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/glir.py", line 787, in _parse
    ob.set_data(*args)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/glir.py", line 929, in set_data
    raise RuntimeError("Shader compilation error in %s:\n%s" %
RuntimeError: Shader compilation error in GL_VERTEX_SHADER:

________________________________________________________________________________
----------------------------- Captured Qt messages -----------------------------
    QtWarningMsg: QMainWindow::saveState(): 'objectName' not set for QDockWidget 0x56521db4fc60 ';
    QtWarningMsg: QMainWindow::saveState(): 'objectName' not set for QDockWidget 0x56521644a160 ';
----------------------------- Captured stderr call -----------------------------
WARNING: Error drawing visual <Text at 0x7f3d2b651a90>
Exceptions caught in Qt event loop:
________________________________________________________________________________
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/app/backends/_qt.py", line 825, in paintGL
    self._vispy_canvas.events.draw(region=None)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/util/event.py", line 455, in __call__
    self._invoke_callback(cb, event)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/util/event.py", line 473, in _invoke_callback
    _handle_exception(self.ignore_callback_errors,
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/util/event.py", line 471, in _invoke_callback
    cb(event)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/scene/canvas.py", line 217, in on_draw
    self._draw_scene()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/scene/canvas.py", line 266, in _draw_scene
    self.draw_visual(self.scene)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/scene/canvas.py", line 304, in draw_visual
    node.draw()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/visuals/visual.py", line 595, in draw
    v.draw()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/scene/visuals.py", line 99, in draw
    self._visual_superclass.draw(self)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/visuals/visual.py", line 442, in draw
    self._program.draw(self._vshare.draw_mode,
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/visuals/shaders/program.py", line 101, in draw
    Program.draw(self, *args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/program.py", line 533, in draw
    canvas.context.flush_commands()
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/context.py", line 176, in flush_commands
    self.glir.flush(self.shared.parser)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/glir.py", line 572, in flush
    self._shared.flush(parser)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/glir.py", line 494, in flush
    parser.parse(self._filter(self.clear(), parser))
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/glir.py", line 819, in parse
    self._parse(command)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/glir.py", line 787, in _parse
    ob.set_data(*args)
  File "/opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/vispy/gloo/glir.py", line 929, in set_data
    raise RuntimeError("Shader compilation error in %s:\n%s" %
RuntimeError: Shader compilation error in GL_VERTEX_SHADER:

________________________________________________________________________________
------------------------------ Captured log call -------------------------------
WARNING  vispy:visual.py:445 Error drawing visual <Text at 0x7f3d2b651a90>
=============================== warnings summary ===============================
test_docs.py::test_doc_code_cells[tutorials/index.md]
  /opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/ipykernel/zmqshell.py:57: DeprecationWarning: ipykernel.datapub is deprecated. It has moved to ipyparallel.datapub
    from ipykernel.datapub import ZMQDataPublisher

test_docs.py::test_doc_code_cells[tutorials/index.md]
  /opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/ipykernel/datapub.py:21: DeprecationWarning: ipykernel.serialize is deprecated. It has moved to ipyparallel.serialize
    from ipykernel.serialize import serialize_object

test_docs.py::test_doc_code_cells[tutorials/index.md]
  /opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/ipykernel/serialize.py:25: DeprecationWarning: ipykernel.pickleutil is deprecated. It has moved to ipyparallel.
    from ipykernel.pickleutil import (

test_docs.py::test_doc_code_cells[tutorials/index.md]
  /opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/ipykernel/pickleutil.py:26: DeprecationWarning: ipykernel.codeutil is deprecated since IPykernel 4.3.1. It has moved to ipyparallel.serialize
    from ipykernel import codeutil

test_docs.py::test_doc_code_cells[tutorials/index.md]
  /opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/ipykernel/iostream.py:9: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    from imp import lock_held as import_lock_held

test_docs.py::test_doc_code_cells[guides/stable/magicgui.md]
  /opt/hostedtoolcache/Python/3.9.4/x64/lib/python3.9/site-packages/magicgui/widgets/_bases/ranged_widget.py:28: FutureWarning: The 'maximum' keyword arguments has been changed to 'max'. In the future this will raise an exception
  
    warn(

-- Docs: https://docs.pytest.org/en/stable/warnings.html
=========================== short test summary info ============================
FAILED test_docs.py::test_doc_code_cells[guides/stable/magicgui.md]
=================== 1 failed, 8 passed, 6 warnings in 14.88s ===================
```

**Comment by GenevieveBuckley** [comment]
@tlambert03 it might be a coincidence this happened while testing the magicgui docs, but maybe you'd like to take a quick look at it.

**Comment by tlambert03** [comment]
rerunning now to see if it's consistent.  strange because this PR doesn't seem to have touched anything about the tests, which have been consistently passing otherwise 🤔

**Comment by GenevieveBuckley** [comment]
Hm, maybe it's just flaky? If that's the case we can go ahead and close this issue.
