### ISSUE TITLE
Some screenshots not being rendered

### ISSUE THREAD

**Issue by codemonkey800** [napari/napari.github.io#172]
I noticed that some of the screenshots from the code examples are no longer rendering during deployment. Here's an example from https://napari.org/tutorials/fundamentals/viewer.html:

![image](https://user-images.githubusercontent.com/2176050/134423060-cb442fbe-5acc-439e-99c1-1ddae835750b.png)

And here's the same page when built locally:

![image](https://user-images.githubusercontent.com/2176050/134423127-f27b19b5-0b85-478e-a3a5-22c5e8f0cddd.png)

**Comment by alisterburt** [comment]
I’m not sure what’s going on with the site (lots of activity on the repo!) but if it’s still jupyter-book I noticed this same issue if there were cells tagged with ‘remove-cell’ in the source

**Comment by alisterburt** [comment]
Again, this was only in CI not when built locally

**Comment by GenevieveBuckley** [comment]
Do we think it's related to https://github.com/napari/napari.github.io/issues/161?

**Comment by GenevieveBuckley** [comment]
@alisterburt the `nbscreenshot` commands are all marked `[hide-input]`. The only `[remove-cell]` tags I see are for closing all the opened viewers, and once for changing the theme back to dark mode.

Jupytext source code: https://github.com/napari/napari.github.io/blob/main/tutorials/fundamentals/viewer.md

**Comment by alisterburt** [comment]
@GenevieveBuckley this matches the behaviour that I was seeing - the presence of [remove-cell] anywhere stopped images from being correctly rendered elsewhere in the document. e.g. [this napari workshop](https://github.com/alisterburt/napari-workshops/blob/main/napari-workshops/notebooks/intro_bioimage_visualization.md) 

I haven't found a solution yet besides building locally but it's almost certainly some easy fix

**Comment by GenevieveBuckley** [comment]
> @GenevieveBuckley this matches the behaviour that I was seeing - the presence of [remove-cell] anywhere stopped images from being correctly rendered elsewhere in the document. e.g. [this napari workshop](https://github.com/alisterburt/napari-workshops/blob/main/napari-workshops/notebooks/intro_bioimage_visualization.md)
> 
> I haven't found a solution yet besides building locally but it's almost certainly some easy fix

Wait, really? `[remove-cell]` being **anywhere** in the notebook has caused problems for unrelated cells in the notebook? That seems like a problem...

**Comment by alisterburt** [comment]
yep! very strange. This only happens for me when building docs on CI, not when building locally so I haven't got it figured out

**Comment by GenevieveBuckley** [comment]
@alisterburt would you also be kind enough to give us the details of your local environment?
* Operating system
* Python version
* conda list / pip list

**Comment by alisterburt** [comment]
sure!
- MacOS 11.5.2
- python 3.9.6 (conda-forge)
conda list:
```
# packages in environment at /opt/homebrew/Caskroom/miniforge/base/envs/napari-workshop:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
anyio                     3.3.0                    pypi_0    pypi
appdirs                   1.4.4                    pypi_0    pypi
appnope                   0.1.2           py39hecd8cb5_1001  
argon2-cffi               20.1.0           py39h9ed2024_1  
async_generator           1.10               pyhd3eb1b0_0  
attrs                     20.3.0                   pypi_0    pypi
babel                     2.9.1                    pypi_0    pypi
backcall                  0.2.0              pyhd3eb1b0_0  
beautifulsoup4            4.9.3                    pypi_0    pypi
bleach                    4.0.0              pyhd3eb1b0_0  
ca-certificates           2021.7.5             hecd8cb5_1  
cachey                    0.2.1                    pypi_0    pypi
cellpose                  0.6.5                    pypi_0    pypi
cellpose-napari           0.1.3                    pypi_0    pypi
certifi                   2021.5.30        py39hecd8cb5_0  
cffi                      1.14.6           py39h2125817_0  
charset-normalizer        2.0.4                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
cloudpickle               1.6.0                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
cycler                    0.10.0                   pypi_0    pypi
dask                      2021.8.0                 pypi_0    pypi
debugpy                   1.4.1                    pypi_0    pypi
decorator                 5.0.9              pyhd3eb1b0_0  
defusedxml                0.7.1              pyhd3eb1b0_0  
docstring-parser          0.10                     pypi_0    pypi
docutils                  0.16                     pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
freetype-py               2.2.0                    pypi_0    pypi
fsspec                    2021.7.0                 pypi_0    pypi
gitdb                     4.0.7                    pypi_0    pypi
gitpython                 3.1.18                   pypi_0    pypi
greenlet                  1.1.1                    pypi_0    pypi
heapdict                  1.0.1                    pypi_0    pypi
hsluv                     5.0.2                    pypi_0    pypi
icu                       58.2                 h0a44026_3  
idna                      3.2                      pypi_0    pypi
imagecodecs               2021.8.26                pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imagesize                 1.2.0                    pypi_0    pypi
importlib-metadata        4.6.4                    pypi_0    pypi
importlib_metadata        3.10.0               hd3eb1b0_0  
ipykernel                 6.2.0                    pypi_0    pypi
ipython                   7.26.0           py39h01d92e1_0  
ipython_genutils          0.2.0              pyhd3eb1b0_1  
ipywidgets                7.6.3              pyhd3eb1b0_1  
jedi                      0.18.0           py39hecd8cb5_1  
jinja2                    3.0.1              pyhd3eb1b0_0  
jpeg                      9b                   he5867d9_2  
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0            py39hecd8cb5_7  
jupyter-book              0.11.2                   pypi_0    pypi
jupyter-cache             0.4.3                    pypi_0    pypi
jupyter-client            7.0.1                    pypi_0    pypi
jupyter-server            1.10.2                   pypi_0    pypi
jupyter-server-mathjax    0.2.3                    pypi_0    pypi
jupyter-sphinx            0.3.2                    pypi_0    pypi
jupyter_client            6.1.12             pyhd3eb1b0_0  
jupyter_console           6.4.0              pyhd3eb1b0_0  
jupyter_core              4.7.1            py39hecd8cb5_0  
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1  
jupytext                  1.10.3                   pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
latexcodec                2.0.1                    pypi_0    pypi
libcxx                    10.0.0                        1  
libffi                    3.3                  hb1e8313_2  
libpng                    1.6.37               ha441bb4_0  
libsodium                 1.0.18               h1de35cc_0  
linkify-it-py             1.0.1                    pypi_0    pypi
llvmlite                  0.37.0                   pypi_0    pypi
locket                    0.2.1                    pypi_0    pypi
magicgui                  0.2.10                   pypi_0    pypi
markdown-it-py            0.6.2                    pypi_0    pypi
markupsafe                2.0.1            py39h9ed2024_0  
matplotlib                3.4.3                    pypi_0    pypi
matplotlib-inline         0.1.2              pyhd3eb1b0_2  
mdit-py-plugins           0.2.6                    pypi_0    pypi
mistune                   0.8.4           py39h9ed2024_1000  
myst-nb                   0.12.3                   pypi_0    pypi
myst-parser               0.13.7                   pypi_0    pypi
napari                    0.4.11rc2                pypi_0    pypi
napari-console            0.0.3                    pypi_0    pypi
napari-plugin-engine      0.1.9                    pypi_0    pypi
napari-svg                0.1.5                    pypi_0    pypi
natsort                   7.1.1                    pypi_0    pypi
nbclient                  0.5.4                    pypi_0    pypi
nbconvert                 5.6.1                    pypi_0    pypi
nbdime                    3.1.0                    pypi_0    pypi
nbformat                  5.1.3              pyhd3eb1b0_0  
ncurses                   6.2                  h0a44026_1  
nest-asyncio              1.5.1              pyhd3eb1b0_0  
networkx                  2.6.2                    pypi_0    pypi
notebook                  6.4.3            py39hecd8cb5_0  
numba                     0.54.0                   pypi_0    pypi
numpy                     1.20.3                   pypi_0    pypi
numpydoc                  1.1.0                    pypi_0    pypi
opencv-python-headless    4.5.3.56                 pypi_0    pypi
openssl                   1.1.1k               h9ed2024_0  
packaging                 21.0               pyhd3eb1b0_0  
pandocfilters             1.4.3            py39hecd8cb5_1  
parso                     0.8.2              pyhd3eb1b0_0  
partd                     1.2.0                    pypi_0    pypi
pexpect                   4.8.0              pyhd3eb1b0_3  
pickleshare               0.7.5           pyhd3eb1b0_1003  
pillow                    8.3.1                    pypi_0    pypi
pint                      0.17                     pypi_0    pypi
pip                       21.2.4           py37hecd8cb5_0  
pooch                     1.4.0                    pypi_0    pypi
prometheus_client         0.11.0             pyhd3eb1b0_0  
prompt-toolkit            3.0.19                   pypi_0    pypi
prompt_toolkit            3.0.17               hd3eb1b0_0  
psutil                    5.8.0                    pypi_0    pypi
ptyprocess                0.7.0              pyhd3eb1b0_2  
pybtex                    0.24.0                   pypi_0    pypi
pybtex-docutils           1.0.1                    pypi_0    pypi
pycparser                 2.20                       py_2  
pydantic                  1.8.2                    pypi_0    pypi
pydata-sphinx-theme       0.6.3                    pypi_0    pypi
pygments                  2.10.0             pyhd3eb1b0_0  
pyopengl                  3.1.5                    pypi_0    pypi
pyparsing                 2.4.7              pyhd3eb1b0_0  
pyqt                      5.9.2            py39h23ab428_6  
pyqt5                     5.15.4                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.9.0                   pypi_0    pypi
pyrsistent                0.18.0           py39h9ed2024_0  
python                    3.9.6                h88f2d9e_1  
python-dateutil           2.8.2              pyhd3eb1b0_0  
pytz                      2021.1                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.2.1           py39h23ab428_1  
qt                        5.9.7                h468cd18_1  
qtconsole                 5.1.0              pyhd3eb1b0_0  
qtpy                      1.9.0                      py_0  
readline                  8.1                  h9ed2024_0  
requests                  2.26.0                   pypi_0    pypi
requests-unixsocket       0.2.0                    pypi_0    pypi
scikit-image              0.18.2                   pypi_0    pypi
scipy                     1.7.1                    pypi_0    pypi
send2trash                1.8.0                    pypi_0    pypi
setuptools                52.0.0           py39hecd8cb5_0  
sip                       4.19.13          py39h23ab428_0  
six                       1.16.0             pyhd3eb1b0_0  
smmap                     4.0.0                    pypi_0    pypi
sniffio                   1.2.0                    pypi_0    pypi
snowballstemmer           2.1.0                    pypi_0    pypi
soupsieve                 2.2.1                    pypi_0    pypi
sphinx                    3.5.4                    pypi_0    pypi
sphinx-book-theme         0.1.2                    pypi_0    pypi
sphinx-comments           0.0.3                    pypi_0    pypi
sphinx-copybutton         0.4.0                    pypi_0    pypi
sphinx-external-toc       0.2.3                    pypi_0    pypi
sphinx-jupyterbook-latex  0.4.2                    pypi_0    pypi
sphinx-multitoc-numbering 0.1.3                    pypi_0    pypi
sphinx-panels             0.5.2                    pypi_0    pypi
sphinx-thebe              0.0.8                    pypi_0    pypi
sphinx-togglebutton       0.2.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                    pypi_0    pypi
sphinxcontrib-bibtex      2.2.1                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.2                    pypi_0    pypi
sphinxcontrib-htmlhelp    2.0.0                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.3                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.5                    pypi_0    pypi
sqlalchemy                1.4.23                   pypi_0    pypi
sqlite                    3.36.0               hce871da_0  
superqt                   0.2.3                    pypi_0    pypi
terminado                 0.11.1                   pypi_0    pypi
testpath                  0.5.0              pyhd3eb1b0_0  
tifffile                  2021.8.8                 pypi_0    pypi
tk                        8.6.10               hb0a8c7a_0  
toml                      0.10.2                   pypi_0    pypi
toolz                     0.11.1                   pypi_0    pypi
torch                     1.9.0                    pypi_0    pypi
tornado                   6.1              py39h9ed2024_0  
tqdm                      4.62.1                   pypi_0    pypi
traitlets                 5.0.5              pyhd3eb1b0_0  
typing-extensions         3.10.0.0                 pypi_0    pypi
tzdata                    2021a                h5d7bf9c_0  
uc-micro-py               1.0.1                    pypi_0    pypi
urllib3                   1.26.6                   pypi_0    pypi
vispy                     0.8.0                    pypi_0    pypi
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    pypi_0    pypi
websocket-client          1.2.1                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_0  
widgetsnbextension        3.5.1            py39hecd8cb5_0  
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h1de35cc_0  
zeromq                    4.3.4                h23ab428_0  
zipp                      3.5.0              pyhd3eb1b0_0  
zlib                      1.2.11               h1de35cc_3  
```

**Comment by GenevieveBuckley** [comment]
At the meeting today it was suggested that we see this error on Linux (but not for people on Macs, etc.)

**Comment by alisterburt** [comment]
hmm, slightly more problematic - is running the deploy workflow on macos too hacky a solution? seems like it shouldn't be necessary but might solve the problem quickly...

**Comment by codemonkey800** [comment]
I ran the napari.org deploy workflow using the `macos-11` (Big Sur) runner and it's still having the same problems with images not rendering in CI 😢 

- [Staging `deploy` Workflow](https://github.com/chanzuckerberg/napari.github.io/runs/3771227916?check_suite_focus=true)
- [Staging Site](https://napari.staging.imaging.cziscience.com/tutorials/fundamentals/viewer.html)

The link to the staging site above should have 9 screenshots (6 rendered, 3 static), but it only has the 3 static screenshots.

---

I'm also seeing Tornado errors (#161) in the CI, but I'm not sure if they're related


```
ERROR:tornado.general:Uncaught exception in ZMQStream callback
Traceback (most recent call last):
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/zmq/eventloop/zmqstream.py", line 431, in _run_callback
    callback(*args, **kwargs)
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_client/threaded.py", line 121, in _handle_recv
    msg_list = self.ioloop._asyncio_event_loop.run_until_complete(get_msg(future_msg))
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 592, in run_until_complete
    self._check_running()
  File "/Users/runner/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 554, in _check_running
    raise RuntimeError(
RuntimeError: Cannot run the event loop while another loop is running
ERROR:tornado.general:Uncaught exception in zmqstream callback
```

I wonder if there's something special about my Conda Forge environment 🤔

**Comment by GenevieveBuckley** [comment]
I would guess that yes, those tornado errors are related. Hmm...

**Comment by neuromusic** [comment]
copy change: delete "and make sure you've selected enough categories"

**Comment by melissawm** [comment]
I believe this has been solved, anyone else experiencing this or can we close?

**Comment by melissawm** [comment]
I am closing this as it seems to be resolved, please reopen otherwise!
